#!/usr/bin/env python3
"""
Clash Rules Auto-Merge Script (Conservative Mode)
Merge upstream rules from blackmatrix7 into targeted rule files only.
Preserves our curated proxy/direct/reject lists (no upstream merge - too massive).

Source mapping:
  apple, steam, ai, icloud  -> blackmatrix7 (targeted supplements)
  reject, proxy, direct     -> MANUAL only (upstream too large)
  private, lancidr, etc.    -> CUSTOM only
"""

import os
import re
import urllib.request
import urllib.error
import time

REPO_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ======== Upstream Sources (blackmatrix7 only) ========

BLACKMATRIX7_URLS = {
    "steam": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list",
    "apple": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list",
    "icloud": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/iCloud/iCloud.list",
    "ai": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list",
}

# Rules sourced from blackmatrix7
BM7_TARGETS = {"steam", "apple", "icloud", "ai"}

# Rules that are manual-only (no auto-merge)
MANUAL_ONLY = {"reject", "proxy", "direct"}

# Rules that are custom-only (no upstream at all)
CUSTOM_ONLY = {"private", "lancidr", "telegramcidr", "applications"}


def fetch_url(url, retries=2):
    """Fetch URL content with retries."""
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url, headers={
                "User-Agent": "Mozilla/5.0 (compatible; ClashRulesBot/1.0)"
            })
            with urllib.request.urlopen(req, timeout=15) as resp:
                return resp.read().decode("utf-8", errors="replace")
        except Exception as e:
            if attempt < retries - 1:
                time.sleep(2)
                continue
            print(f"  [WARN] Failed: {url} - {e}")
            return None


def parse_clash_format(content):
    """Parse standard Clash rule format -> set of rule strings."""
    rules = set()
    if not content:
        return rules

    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # Skip blackmatrix7 metadata lines
        if re.match(r"^# (NAME|AUTHOR|REPO|UPDATED|DOMAIN|IP-CIDR|PROCESS|TOTAL)", line, re.IGNORECASE):
            continue
        rules.add(line)

    return rules


def read_our_rules(filepath):
    """Read our rule file -> (header_lines, rule_set)."""
    if not os.path.exists(filepath):
        return [], set()

    header = []
    rules = set()
    in_header = True

    with open(filepath, "r", encoding="utf-8") as f:
        lines = f.readlines()

    for line in lines:
        stripped = line.strip()
        if in_header and (stripped.startswith("#") or stripped == ""):
            header.append(line)
        elif not stripped:
            header.append(line)
        else:
            in_header = False
            # Process this and remaining lines as rules
            rules.add(stripped)

    # If header ended but we already processed the first rule line above
    # The for loop handles it correctly since we only add stripped non-header lines

    return header, rules


def write_rules(filepath, header, rules):
    """Write rule file: header + sorted unique rules."""
    os.makedirs(os.path.dirname(filepath), exist_ok=True)

    def sort_key(rule):
        prefixes = {
            "DOMAIN,": 0,
            "DOMAIN-SUFFIX,": 1,
            "DOMAIN-KEYWORD,": 2,
            "IP-CIDR,": 3,
            "IP-CIDR6,": 4,
            "GEOIP,": 5,
            "PROCESS-NAME,": 6,
            "MATCH,": 7,
        }
        for prefix, order in prefixes.items():
            if rule.startswith(prefix):
                return (order, rule.lower())
        return (99, rule.lower())

    sorted_rules = sorted(rules, key=sort_key)

    with open(filepath, "w", encoding="utf-8") as f:
        h = "".join(header).rstrip("\n") + "\n\n"
        f.write(h)
        for rule in sorted_rules:
            f.write(rule.rstrip("\n") + "\n")

    print(f"  -> Wrote {len(sorted_rules)} rules")


def merge_file(name, filepath, upstream_urls):
    """Merge upstream rules into one of our rule files."""
    print(f"\n[Processing] {name}.txt")

    header, our_rules = read_our_rules(filepath)
    print(f"  [Current] {len(our_rules)} rules")

    if not header:
        header = [f"# {name} rules - merged from blackmatrix7\n",
                  f"# Generated by merge_rules.py\n"]

    all_rules = set(our_rules)

    for src_name, url in upstream_urls:
        print(f"  [Fetch] {src_name}...")
        content = fetch_url(url)
        if not content:
            continue

        upstream_rules = parse_clash_format(content)
        new_rules = upstream_rules - our_rules
        print(f"    -> {src_name}: {len(upstream_rules)} rules, {len(new_rules)} new")
        all_rules |= upstream_rules

    write_rules(filepath, header, all_rules)
    delta = len(all_rules) - len(our_rules)
    print(f"  [Done] {len(our_rules)} -> {len(all_rules)} ({'+' if delta >= 0 else ''}{delta})")


def main():
    print("=" * 50)
    print("Clash Rules Auto-Merge (Conservative)")
    print("=" * 50)

    # Process blackmatrix7-sourced files
    for name in sorted(BM7_TARGETS):
        filepath = os.path.join(REPO_DIR, f"{name}.txt")
        url = BLACKMATRIX7_URLS.get(name)
        if url:
            merge_file(name, filepath, [(name, url)])

    # Report manual-only files
    print("\n[Manual-only files] (no auto-merge, curated manually):")
    for name in sorted(MANUAL_ONLY):
        filepath = os.path.join(REPO_DIR, f"{name}.txt")
        with open(filepath, "r", encoding="utf-8") as f:
            count = sum(1 for line in f if line.strip() and not line.startswith("#"))
        print(f"  [Preserved] {name}.txt: {count} rules")

    # Report custom-only files
    print("\n[Custom-only files] (no upstream source):")
    for name in sorted(CUSTOM_ONLY):
        filepath = os.path.join(REPO_DIR, f"{name}.txt")
        with open(filepath, "r", encoding="utf-8") as f:
            count = sum(1 for line in f if line.strip() and not line.startswith("#"))
        print(f"  [Preserved] {name}.txt: {count} rules")

    print("\n" + "=" * 50)
    print("Merge complete!")
    print("=" * 50)


if __name__ == "__main__":
    main()